version: "3.7"
services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    container_name: exam_restaurant_service_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty!234
      - POSTGRES_DB=restaurants
    ports:
      - '6969:5432'
  redis_db:
    image: redis:6.2-alpine
    restart: always
    container_name: exam_restaurant_service_redis
    environment:
      - REDIS_PASSWORD=Qwerty!234
    ports:
      - '6380:6379'
