name: Setup environment
description: 'Action used to setup the environment'

runs:
  using: composite
  steps:
    # Uncomment if you are using a docker compose to setup your environment
    # - name: Setup environment
    #   run: |
    #     docker-compose docker-compose.yaml up -d
    #     sleep 5

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven
